"""
Dockerfile Generator Service
Generates framework-specific Dockerfiles with build-time environment variable support.
"""

class DockerfileGenerator:
    """Generate framework-specific Dockerfiles."""
    
    @staticmethod
    def generate_nextjs_dockerfile(env_vars: dict) -> str:
        """
        Generate Next.js Dockerfile with build-time environment variables.
        
        Args:
            env_vars: Dictionary of environment variables (e.g., {"NEXT_PUBLIC_API_URL": "http://..."})
            
        Returns:
            Dockerfile content as string
        """
        # Build ARG and ENV declarations for all NEXT_PUBLIC_* variables
        arg_declarations = []
        env_declarations = []
        
        for key, value in env_vars.items():
            if key.startswith("NEXT_PUBLIC_"):
                arg_declarations.append(f"ARG {key}")
                env_declarations.append(f"ENV {key}=${{{key}}}")
        
        args_block = "\n".join(arg_declarations) if arg_declarations else "# No NEXT_PUBLIC_ variables"
        envs_block = "\n".join(env_declarations) if env_declarations else ""
        
        dockerfile = f"""# Next.js Multi-Stage Dockerfile with Build-Time Environment Variables
# Generated by Capsule Deploy Portal

FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app

# Accept build arguments for Next.js environment variables
{args_block}
{envs_block}

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js build
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && \\
    adduser --system --uid 1001 nextjs

# Copy built assets
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

CMD ["node", "server.js"]
"""
        return dockerfile

    @staticmethod
    def generate_vite_dockerfile(env_vars: dict) -> str:
        """
        Generate Vite Dockerfile with build-time environment variables.
        
        Args:
            env_vars: Dictionary of environment variables (e.g., {"VITE_API_URL": "http://..."})
            
        Returns:
            Dockerfile content as string
        """
        # Build ARG and ENV declarations for all VITE_* variables
        arg_declarations = []
        env_declarations = []
        
        for key, value in env_vars.items():
            if key.startswith("VITE_"):
                arg_declarations.append(f"ARG {key}")
                env_declarations.append(f"ENV {key}=${{{key}}}")
        
        args_block = "\n".join(arg_declarations) if arg_declarations else "# No VITE_ variables"
        envs_block = "\n".join(env_declarations) if env_declarations else ""
        
        dockerfile = f"""# Vite Multi-Stage Dockerfile with Build-Time Environment Variables
# Generated by Capsule Deploy Portal

FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app

# Accept build arguments for Vite environment variables
{args_block}
{envs_block}

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Vite build
RUN npm run build

FROM nginx:alpine AS runner
WORKDIR /app

# Copy built assets to nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config if exists
COPY nginx.conf /etc/nginx/conf.d/default.conf 2>/dev/null || true

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
"""
        return dockerfile

    @staticmethod
    def generate_cra_dockerfile(env_vars: dict) -> str:
        """
        Generate Create React App Dockerfile with build-time environment variables.
        
        Args:
            env_vars: Dictionary of environment variables (e.g., {"REACT_APP_API_URL": "http://..."})
            
        Returns:
            Dockerfile content as string
        """
        # Build ARG and ENV declarations for all REACT_APP_* variables
        arg_declarations = []
        env_declarations = []
        
        for key, value in env_vars.items():
            if key.startswith("REACT_APP_"):
                arg_declarations.append(f"ARG {key}")
                env_declarations.append(f"ENV {key}=${{{key}}}")
        
        args_block = "\n".join(arg_declarations) if arg_declarations else "# No REACT_APP_ variables"
        envs_block = "\n".join(env_declarations) if env_declarations else ""
        
        dockerfile = f"""# Create React App Multi-Stage Dockerfile with Build-Time Environment Variables
# Generated by Capsule Deploy Portal

FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app

# Accept build arguments for React environment variables
{args_block}
{envs_block}

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# React build
RUN npm run build

FROM nginx:alpine AS runner
WORKDIR /app

# Copy built assets to nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Copy custom nginx config if exists
COPY nginx.conf /etc/nginx/conf.d/default.conf 2>/dev/null || true

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
"""
        return dockerfile
